"""empty message

Revision ID: 00653731aea9
Revises: d43ef5224ac4
Create Date: 2024-12-06 18:12:45.210072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00653731aea9'
down_revision = 'd43ef5224ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'inventory_item', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
